Repository The-Scratch-Channel/tsc-web-client, pull requests merged in 2025-08, with the labels that each got.

#50 Added about page
  .gitignore
  src/App.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/pages/About.jsx
  src/styles/index-revamp.css
Labels: enhancement, update, size/M

#84 Firebase merge
  package-lock.json
  package.json
  src/App.jsx
  src/components/Header.jsx
  src/firebaseConfig.js
  src/pages/Account.jsx
  src/pages/ArticlePage.jsx
  src/pages/Login.jsx
  src/pages/MainContent.jsx
  src/pages/SignUp.jsx
  src/pages/createArticles.jsx
Labels: update, size/XL

#88 preventing merge conflict
  .github/workflows/commit_logger.yml
  public/favicon-alt.svg
Labels: size/M
